[build]
  # Comando de build do projeto
  command = "npm run build"
  
  # Diretório onde ficam os arquivos de build
  publish = "dist"

[build.environment]
  # Configurações de ambiente para o build
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Configurações para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers para arquivos estáticos (cache)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para o service worker (se houver)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configurações de formulário (caso precise de integração direta com Netlify)
[forms]
  # Se quiser backup dos formulários também no Netlify
  # form-name = "event-registration"

# Configurações de funções serverless (se precisar)
[functions]
  # directory = "netlify/functions"

# Configurações de desenvolvimento local
[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080
  publish = "dist"
